In [1]:
import pandas as pd

In [2]:
# Load dataset
df_genres = pd.read_csv('genres.csv')

In [3]:
df_genres

    genre_id       genre_name
0         28           Action
1         12        Adventure
2         16        Animation
3         35           Comedy
4         80            Crime
5         99      Documentary
6         18            Drama
7      10751           Family
8         14          Fantasy
9         36          History
10        27           Horror
11     10402            Music
12      9648          Mystery
13     10749          Romance
14       878  Science Fiction
15     10770         TV Movie
16        53         Thriller
17     10752              War
18        37          Western

In [4]:
df_genres.head()

   genre_id genre_name
0        28     Action
1        12  Adventure
2        16  Animation
3        35     Comedy
4        80      Crime

In [5]:
df_genres.columns

Index(['genre_id', 'genre_name'], dtype='str')

In [6]:
df_genres.shape

(19, 2)

In [7]:
df_genres.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   genre_id    19 non-null     int64
 1   genre_name  19 non-null     str
dtypes: int64(1), str(1)
memory usage: 573.0 bytes

In [8]:
#check duplicate rows
print("Duplicate rows:", df_genres.duplicated().sum())

Duplicate rows: 0

In [9]:
# 1. Text normalization & whitespace removal
df_genres['genre_name'] = df_genres['genre_name'].astype(str).str.strip()

In [10]:
df_genres["genre_name"] = ( df_genres["genre_name"] .fillna("Unknown") .astype(str) .str.strip() .str.title() )

In [11]:
df_genres

    genre_id       genre_name
0         28           Action
1         12        Adventure
2         16        Animation
3         35           Comedy
4         80            Crime
5         99      Documentary
6         18            Drama
7      10751           Family
8         14          Fantasy
9         36          History
10        27           Horror
11     10402            Music
12      9648          Mystery
13     10749          Romance
14       878  Science Fiction
15     10770         Tv Movie
16        53         Thriller
17     10752              War
18        37          Western

In [12]:
#2. Remove duplicate genre IDs
df_genres_clean = df_genres.drop_duplicates(subset=['genre_id'], keep='first')

In [13]:
df_genres_clean

    genre_id       genre_name
0         28           Action
1         12        Adventure
2         16        Animation
3         35           Comedy
4         80            Crime
5         99      Documentary
6         18            Drama
7      10751           Family
8         14          Fantasy
9         36          History
10        27           Horror
11     10402            Music
12      9648          Mystery
13     10749          Romance
14       878  Science Fiction
15     10770         Tv Movie
16        53         Thriller
17     10752              War
18        37          Western

In [14]:
# Display cleaned data
print(df_genres.to_string(index=False))

 genre_id      genre_name
       28          Action
       12       Adventure
       16       Animation
       35          Comedy
       80           Crime
       99     Documentary
       18           Drama
    10751          Family
       14         Fantasy
       36         History
       27          Horror
    10402           Music
     9648         Mystery
    10749         Romance
      878 Science Fiction
    10770        Tv Movie
       53        Thriller
    10752             War
       37         Western

In [20]:
# 3. save cleaned dataset
df_genres_clean.to_csv('genres_cleaned.csv', index=False)
print("Genres dataset cleaned successfully!")

Genres dataset cleaned successfully!

In [16]:
df_genres_clean

    genre_id       genre_name
0         28           Action
1         12        Adventure
2         16        Animation
3         35           Comedy
4         80            Crime
5         99      Documentary
6         18            Drama
7      10751           Family
8         14          Fantasy
9         36          History
10        27           Horror
11     10402            Music
12      9648          Mystery
13     10749          Romance
14       878  Science Fiction
15     10770         Tv Movie
16        53         Thriller
17     10752              War
18        37          Western

In [17]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:root@localhost/movies"
)

print("Engine created successfully!")

Engine created successfully!

In [18]:
df_genres_clean.to_sql(
     'genres',
    if_exists='replace',
    con=engine,
    index=False)

19