In [ ]:
import pandas as pd

In [7]:
# 1. Read input CSV files
df = pd.read_csv('cast.csv')
df_movies = pd.read_csv('movies_cleaned.csv')

In [8]:
df

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
0,1,157336,10297,Matthew McConaughey,Cooper,0
1,2,157336,1813,Anne Hathaway,Brand,1
2,3,157336,3895,Michael Caine,Professor Brand,2
3,4,157336,83002,Jessica Chastain,Murph,3
4,5,157336,1893,Casey Affleck,Tom,4
...,...,...,...,...,...,...
24912,17699,58224,9048,Clark Gregg,Nat Jones,5
24913,20628,239571,61011,Clarke Peters,Morgan Dupree,6
24914,12827,1948,39391,Edi Gathegi,Haitian Cabbie,7
24915,17362,10494,84509,Yosuke Akimoto,Tejima (voice),6
24916,517,105,1067,Marc McClure,Dave McFly,6

In [9]:
df.head()

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
0,1,157336,10297,Matthew McConaughey,Cooper,0
1,2,157336,1813,Anne Hathaway,Brand,1
2,3,157336,3895,Michael Caine,Professor Brand,2
3,4,157336,83002,Jessica Chastain,Murph,3
4,5,157336,1893,Casey Affleck,Tom,4

In [10]:
df.columns

Index(['cast_row_id', 'movie_id', 'person_id', 'actor_name', 'character_name',
       'cast_order'],
      dtype='str')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24917 entries, 0 to 24916
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cast_row_id     24917 non-null  int64
 1   movie_id        24917 non-null  int64
 2   person_id       24917 non-null  int64
 3   actor_name      24917 non-null  str
 4   character_name  24906 non-null  str
 5   cast_order      24917 non-null  int64
dtypes: int64(4), str(2)
memory usage: 1.7 MB

In [13]:
df.shape

(24917, 6)

In [12]:
#check duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 15

In [15]:
# 2. Drop duplicate cast records
df_cast_clean = df_cast.drop_duplicates(keep='first').copy()

In [16]:
df_cast_clean

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
0,1,157336,10297,Matthew McConaughey,Cooper,0
1,2,157336,1813,Anne Hathaway,Brand,1
2,3,157336,3895,Michael Caine,Professor Brand,2
3,4,157336,83002,Jessica Chastain,Murph,3
4,5,157336,1893,Casey Affleck,Tom,4
...,...,...,...,...,...,...
24897,24898,19901,77496,Vince Colosimo,Christopher Caruso,5
24898,24899,19901,33182,Jay Laga'aia,Senator Turner,6
24899,24900,19901,76068,Michael Dorman,Frankie Dalton,7
24900,24901,19901,1121519,Harriet Minto-Day,Lisa Barrett,8
24901,24902,19901,61911,Tiffany Lamb,News Reader,9

In [19]:
# 3. Text Normalization & Impute Missing Values 
df_cast_clean['actor_name'] = df_cast_clean['actor_name'].fillna('Unknown').astype(str).str.strip()
df_cast_clean['character_name'] = df_cast_clean['character_name'].fillna('Uncredited / Unknown').astype(str).str.strip()

In [8]:
# 4. Validate foreign key integrity (ensure movie_id exists)
valid_movies = set(df_movies['movie_id'])
df_cast_clean = df_cast_clean[df_cast_clean['movie_id'].isin(valid_movies)]

In [21]:
# 5. Reindex Primary Keys & Enforce Types
df_cast_clean['cast_row_id'] = range(1, len(df_cast_clean) + 1)

df_cast_clean['movie_id'] = df_cast_clean['movie_id'].astype(int)
df_cast_clean['person_id'] = df_cast_clean['person_id'].astype(int)
df_cast_clean['cast_order'] = df_cast_clean['cast_order'].astype(int)

In [23]:
# 5. Export cleaned dataset
df_cast_clean.to_csv('cast_cleaned.csv', index=False)
print("Cleaned cast dataset saved successfully.")

Cleaned cast dataset saved successfully.

In [24]:
df_cast_clean

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
0,1,157336,10297,Matthew McConaughey,Cooper,0
1,2,157336,1813,Anne Hathaway,Brand,1
2,3,157336,3895,Michael Caine,Professor Brand,2
3,4,157336,83002,Jessica Chastain,Murph,3
4,5,157336,1893,Casey Affleck,Tom,4
...,...,...,...,...,...,...
24897,24898,19901,77496,Vince Colosimo,Christopher Caruso,5
24898,24899,19901,33182,Jay Laga'aia,Senator Turner,6
24899,24900,19901,76068,Michael Dorman,Frankie Dalton,7
24900,24901,19901,1121519,Harriet Minto-Day,Lisa Barrett,8
24901,24902,19901,61911,Tiffany Lamb,News Reader,9

In [25]:
df_cast_clean.shape

(24902, 6)

In [26]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:root@localhost/movies"
)

print("Engine created successfully!")

Engine created successfully!

In [27]:
df_cast_clean.to_sql(
     'cast',
    if_exists='replace',
    con=engine,
    index=False)

24902