In [1]:
import pandas as pd

In [2]:
# 1. Load keywords and reference movies table
df_mk = pd.read_csv('movie_keywords.csv')
df_movies = pd.read_csv('movies_cleaned.csv')

In [3]:
df_mk

       movie_id  keyword_id                    keyword_name
0        157336        1612                      spacecraft
1        157336        4776               race against time
2        157336         310  artificial intelligence (a.i.)
3        157336        1432                            nasa
4        157336        1521                       time warp
...         ...         ...                             ...
41696      1271      329753                     epic heroes
41697     10483         378                          prison
41698       111         701                            cuba
41699    339397       10048                 unrequited love
41700      7446      167477                       land mine

[41701 rows x 3 columns]

In [4]:
df_mk.head()

   movie_id  keyword_id                    keyword_name
0    157336        1612                      spacecraft
1    157336        4776               race against time
2    157336         310  artificial intelligence (a.i.)
3    157336        1432                            nasa
4    157336        1521                       time warp

In [6]:
df_mk.columns

Index(['movie_id', 'keyword_id', 'keyword_name'], dtype='str')

In [7]:
df_mk.shape

(41701, 3)

In [8]:
df_mk.info()

<class 'pandas.DataFrame'>
RangeIndex: 41701 entries, 0 to 41700
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      41701 non-null  int64
 1   keyword_id    41701 non-null  int64
 2   keyword_name  41701 non-null  str
dtypes: int64(2), str(1)
memory usage: 1.4 MB

In [17]:
# 2. clean text columns
df_mk['keyword_name'] = df_mk['keyword_name'] .fillna('Unknown').astype(str).str.strip()

In [18]:
#check duplicate rows
print("Duplicate rows:",df_mk.duplicated().sum())

Duplicate rows: 20

In [19]:
# 3. Drop duplicate keyword mappings per movie
df_mk_clean = df_mk.drop_duplicates(subset=['movie_id', 'keyword_id'], keep='first').copy()

In [20]:
df_mk_clean

       movie_id  keyword_id                    keyword_name
0        157336        1612                      spacecraft
1        157336        4776               race against time
2        157336         310  artificial intelligence (a.i.)
3        157336        1432                            nasa
4        157336        1521                       time warp
...         ...         ...                             ...
41676     19901       34079                           death
41677     19901      160153                            dead
41678     19901      232469                    urban gothic
41679     19901      243150                   brutal deaths
41680     19901      325824                         hopeful

[41681 rows x 3 columns]

In [21]:
df_mk.shape, df_mk_clean.shape

((41701, 3), (41681, 3))

In [22]:
# 4. Validate foreign keys (ensure movie_id exists in movies dataset)
valid_movies = set(df_movies['movie_id'])
df_mk_clean = df_mk_clean[df_mk_clean['movie_id'].isin(valid_movies)]

In [27]:
# 5. Enforce integer data types
df_mk['movie_id'] = df_mk['movie_id'].astype(int)
df_mk['keyword_id'] = df_mk['keyword_id'].astype(int)

In [30]:
# 6. Export clean dataset
df_mk_clean.to_csv('movie_keywords_cleaned.csv', index=False)
print("Movie_keywords data cleaned  saved successfully.")

Movie_keywords data cleaned  saved successfully.

In [31]:
df_mk_clean

       movie_id  keyword_id                    keyword_name
0        157336        1612                      spacecraft
1        157336        4776               race against time
2        157336         310  artificial intelligence (a.i.)
3        157336        1432                            nasa
4        157336        1521                       time warp
...         ...         ...                             ...
41676     19901       34079                           death
41677     19901      160153                            dead
41678     19901      232469                    urban gothic
41679     19901      243150                   brutal deaths
41680     19901      325824                         hopeful

[41681 rows x 3 columns]

In [32]:
from sqlalchemy import create_engine
engine=create_engine(
    "mysql+pymysql://root:root@localhost/movies"
)

print("Engine created successfully!")

Engine created successfully!

In [33]:
df_mk_clean.to_sql(
     'movie_keywords',
    if_exists='replace',
    con=engine,
    index=False)

41681