In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load dataset
df = pd.read_csv('movies.csv')

In [3]:
df

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview
0,157336,Interstellar,en,2014-11-05,169,1.650000e+08,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...
1,27205,Inception,en,2010-07-15,148,1.600000e+08,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es..."
2,24428,The Avengers,en,2012-04-25,143,2.200000e+08,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...
3,155,The Dark Knight,en,2008-07-16,152,1.850000e+08,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...
4,19995,Avatar,en,2009-12-16,162,2.370000e+08,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di..."
...,...,...,...,...,...,...,...,...,...,...,...,...
2504,98,Gladiator,en,2000-05-04,155,1.030000e+08,4.655162e+08,38.9610,8.230,21184,Released,"After the death of Emperor Marcus Aurelius, hi..."
2505,1368167,Date Night,en,1995-04-08,88,9.321480e+07,8.759568e+07,8.2930,7.000,1051,Released,Phil and Claire Foster fear that their mild-ma...
2506,1368168,Transformers,en,1987-06-27,144,1.100988e+08,2.747467e+08,6.5902,7.900,4215,Released,Young teenager Sam Witwicky becomes involved i...
2507,1368169,The SpongeBob Movie: Sponge Out of Water,en,2000-01-28,93,3.928488e+07,5.706575e+08,11.3857,7.100,475,Released,Evil pirate Burger Beard is in search of the f...
2508,1368170,Fargo,en,2011-03-08,98,5.425747e+06,4.584468e+07,11.2271,7.900,2514,Released,"Jerry, a small-town Minnesota car salesman is ..."

In [4]:
df.head()

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview
0,157336,Interstellar,en,2014-11-05,169,165000000.0,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...
1,27205,Inception,en,2010-07-15,148,160000000.0,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es..."
2,24428,The Avengers,en,2012-04-25,143,220000000.0,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...
3,155,The Dark Knight,en,2008-07-16,152,185000000.0,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...
4,19995,Avatar,en,2009-12-16,162,237000000.0,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di..."

In [5]:
df.tail()

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview
2504,98,Gladiator,en,2000-05-04,155,1.030000e+08,4.655162e+08,38.9610,8.23,21184,Released,"After the death of Emperor Marcus Aurelius, hi..."
2505,1368167,Date Night,en,1995-04-08,88,9.321480e+07,8.759568e+07,8.2930,7.00,1051,Released,Phil and Claire Foster fear that their mild-ma...
2506,1368168,Transformers,en,1987-06-27,144,1.100988e+08,2.747467e+08,6.5902,7.90,4215,Released,Young teenager Sam Witwicky becomes involved i...
2507,1368169,The SpongeBob Movie: Sponge Out of Water,en,2000-01-28,93,3.928488e+07,5.706575e+08,11.3857,7.10,475,Released,Evil pirate Burger Beard is in search of the f...
2508,1368170,Fargo,en,2011-03-08,98,5.425747e+06,4.584468e+07,11.2271,7.90,2514,Released,"Jerry, a small-town Minnesota car salesman is ..."

In [6]:
df.columns

Index(['movie_id', 'title', 'original_language', 'release_date', 'runtime',
       'budget', 'revenue', 'popularity', 'vote_average', 'vote_count',
       'status', 'overview'],
      dtype='str')

In [7]:
# 1. Check shape
df.shape

(2509, 12)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   movie_id           2509 non-null   int64
 1   title              2509 non-null   str
 2   original_language  2509 non-null   str
 3   release_date       2509 non-null   str
 4   runtime            2509 non-null   int64
 5   budget             2509 non-null   float64
 6   revenue            2509 non-null   float64
 7   popularity         2509 non-null   float64
 8   vote_average       2509 non-null   float64
 9   vote_count         2509 non-null   int64
 10  status             2509 non-null   str
 11  overview           2509 non-null   str
dtypes: float64(4), int64(3), str(5)
memory usage: 989.6 KB

In [9]:
# Copy dataframe
df_clean = df.copy()
print(df_clean.head())

   movie_id            title original_language release_date  runtime  \
0    157336     Interstellar                en   2014-11-05      169
1     27205        Inception                en   2010-07-15      148
2     24428     The Avengers                en   2012-04-25      143
3       155  The Dark Knight                en   2008-07-16      152
4     19995           Avatar                en   2009-12-16      162

        budget       revenue  popularity  vote_average  vote_count    status  \
0  165000000.0  7.466067e+08     73.0452         8.484       40566  Released
1  160000000.0  8.390306e+08     55.8497         8.400       39727  Released
2  220000000.0  1.518816e+09     72.2515         8.062       38993  Released
3  185000000.0  1.004558e+09     60.5510         8.534       36255  Released
4  237000000.0  2.923706e+09     48.1996         7.610       34348  Released

                                            overview
0  The adventures of a group of explorers who mak...
1  Cobb, a skilled thief who commits corporate es...
2  When an unexpected enemy emerges and threatens...
3  Batman raises the stakes in his war on crime. ...
4  In the 22nd century, a paraplegic Marine is di...

In [10]:
# 2. Check duplicate records
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 6

In [11]:
# Remove duplicates
df_clean = df.drop_duplicates()

In [12]:
df_clean

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview
0,157336,Interstellar,en,2014-11-05,169,1.650000e+08,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...
1,27205,Inception,en,2010-07-15,148,1.600000e+08,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es..."
2,24428,The Avengers,en,2012-04-25,143,2.200000e+08,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...
3,155,The Dark Knight,en,2008-07-16,152,1.850000e+08,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...
4,19995,Avatar,en,2009-12-16,162,2.370000e+08,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di..."
...,...,...,...,...,...,...,...,...,...,...,...,...
2498,19901,Daybreakers,en,2010-01-06,98,2.000000e+07,5.141719e+07,6.5762,6.285,2223,Released,"In the year 2019, a plague has transformed alm..."
2505,1368167,Date Night,en,1995-04-08,88,9.321480e+07,8.759568e+07,8.2930,7.000,1051,Released,Phil and Claire Foster fear that their mild-ma...
2506,1368168,Transformers,en,1987-06-27,144,1.100988e+08,2.747467e+08,6.5902,7.900,4215,Released,Young teenager Sam Witwicky becomes involved i...
2507,1368169,The SpongeBob Movie: Sponge Out of Water,en,2000-01-28,93,3.928488e+07,5.706575e+08,11.3857,7.100,475,Released,Evil pirate Burger Beard is in search of the f...
2508,1368170,Fargo,en,2011-03-08,98,5.425747e+06,4.584468e+07,11.2271,7.900,2514,Released,"Jerry, a small-town Minnesota car salesman is ..."

In [13]:
print("Duplicates after:", df_clean.duplicated().sum())

Duplicates after: 0

In [14]:
# 2. Clean string columns
text_cols = df_clean.select_dtypes(include=["str"]).columns

for col in text_cols:
    df_clean[col] = df_clean[col].str.strip()

In [15]:
df_clean[col]

0       The adventures of a group of explorers who mak...
1       Cobb, a skilled thief who commits corporate es...
2       When an unexpected enemy emerges and threatens...
3       Batman raises the stakes in his war on crime. ...
4       In the 22nd century, a paraplegic Marine is di...
                              ...
2498    In the year 2019, a plague has transformed alm...
2505    Phil and Claire Foster fear that their mild-ma...
2506    Young teenager Sam Witwicky becomes involved i...
2507    Evil pirate Burger Beard is in search of the f...
2508    Jerry, a small-town Minnesota car salesman is ...
Name: overview, Length: 2503, dtype: str

In [16]:
# 3. Check missing values
print("\nMissing values:")
print(df_clean.isnull().sum())

Missing values:
movie_id             0
title                0
original_language    0
release_date         0
runtime              0
budget               0
revenue              0
popularity           0
vote_average         0
vote_count           0
status               0
overview             0
dtype: int64

In [17]:
# 5. Convert release_date to datetime
df_clean["release_date"] = pd.to_datetime(
    df_clean["release_date"],errors="coerce")

In [18]:
df_clean

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview
0,157336,Interstellar,en,2014-11-05,169,1.650000e+08,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...
1,27205,Inception,en,2010-07-15,148,1.600000e+08,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es..."
2,24428,The Avengers,en,2012-04-25,143,2.200000e+08,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...
3,155,The Dark Knight,en,2008-07-16,152,1.850000e+08,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...
4,19995,Avatar,en,2009-12-16,162,2.370000e+08,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di..."
...,...,...,...,...,...,...,...,...,...,...,...,...
2498,19901,Daybreakers,en,2010-01-06,98,2.000000e+07,5.141719e+07,6.5762,6.285,2223,Released,"In the year 2019, a plague has transformed alm..."
2505,1368167,Date Night,en,1995-04-08,88,9.321480e+07,8.759568e+07,8.2930,7.000,1051,Released,Phil and Claire Foster fear that their mild-ma...
2506,1368168,Transformers,en,1987-06-27,144,1.100988e+08,2.747467e+08,6.5902,7.900,4215,Released,Young teenager Sam Witwicky becomes involved i...
2507,1368169,The SpongeBob Movie: Sponge Out of Water,en,2000-01-28,93,3.928488e+07,5.706575e+08,11.3857,7.100,475,Released,Evil pirate Burger Beard is in search of the f...
2508,1368170,Fargo,en,2011-03-08,98,5.425747e+06,4.584468e+07,11.2271,7.900,2514,Released,"Jerry, a small-town Minnesota car salesman is ..."

In [19]:
# 6. Check invalid numeric values
print("\nNegative values:")
print("Budget:", (df_clean["budget"] < 0).sum())
print("Revenue:", (df_clean["revenue"] < 0).sum())
print("Runtime:", (df_clean["runtime"] < 0).sum())

Negative values:
Budget: 0
Revenue: 0
Runtime: 0

In [20]:
# 7. Replace invalid negative values with NaN
df_clean.loc[df_clean["budget"] < 0, "budget"] = np.nan
df_clean.loc[df_clean["revenue"] < 0, "revenue"] = np.nan
df_clean.loc[df_clean["runtime"] < 0, "runtime"] = np.nan

In [21]:
# 8. Fill numeric missing values with median
numeric_cols = ["budget", "revenue", "runtime"]

for col in numeric_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

In [22]:
df_clean[col]

0       169.0
1       148.0
2       143.0
3       152.0
4       162.0
        ...
2498     98.0
2505     88.0
2506    144.0
2507     93.0
2508     98.0
Name: runtime, Length: 2503, dtype: float64

In [23]:
# 9. Feature Engineering: Profit
df_clean["profit"] = df_clean["revenue"] - df_clean["budget"]
print(df_clean['profit'])

0       5.816067e+08
1       6.790306e+08
2       1.298816e+09
3       8.195584e+08
4       2.686706e+09
            ...
2498    3.141719e+07
2505   -5.619119e+06
2506    1.646479e+08
2507    5.313726e+08
2508    4.041893e+07
Name: profit, Length: 2503, dtype: float64

In [24]:
# 10. Feature Engineering: ROI (%)
df_clean["roi_pct"] = np.where(df_clean["budget"] > 0,
    ((df_clean["revenue"] - df_clean["budget"]) / df_clean["budget"]) * 100,np.nan)
print(df_clean['roi_pct'])

0        352.488913
1        424.394144
2        590.370689
3        443.004564
4       1133.631235
           ...
2498     157.085940
2505      -6.028140
2506     149.545660
2507    1352.613653
2508     744.946776
Name: roi_pct, Length: 2503, dtype: float64

In [25]:
# Round ROI
df_clean["roi_pct"] = df_clean["roi_pct"].round(2) 
print(df_clean['roi_pct'])

0        352.49
1        424.39
2        590.37
3        443.00
4       1133.63
         ...
2498     157.09
2505      -6.03
2506     149.55
2507    1352.61
2508     744.95
Name: roi_pct, Length: 2503, dtype: float64

In [26]:
# 11. Reset index
df_clean = df_clean.reset_index(drop=True)
print(df_clean)

      movie_id                                     title original_language  \
0       157336                              Interstellar                en
1        27205                                 Inception                en
2        24428                              The Avengers                en
3          155                           The Dark Knight                en
4        19995                                    Avatar                en
...        ...                                       ...               ...
2498     19901                               Daybreakers                en
2499   1368167                                Date Night                en
2500   1368168                              Transformers                en
2501   1368169  The SpongeBob Movie: Sponge Out of Water                en
2502   1368170                                     Fargo                en

     release_date  runtime        budget       revenue  popularity  \
0      2014-11-05    169.0  1.650000e+08  7.466067e+08     73.0452
1      2010-07-15    148.0  1.600000e+08  8.390306e+08     55.8497
2      2012-04-25    143.0  2.200000e+08  1.518816e+09     72.2515
3      2008-07-16    152.0  1.850000e+08  1.004558e+09     60.5510
4      2009-12-16    162.0  2.370000e+08  2.923706e+09     48.1996
...           ...      ...           ...           ...         ...
2498   2010-01-06     98.0  2.000000e+07  5.141719e+07      6.5762
2499   1995-04-08     88.0  9.321480e+07  8.759568e+07      8.2930
2500   1987-06-27    144.0  1.100988e+08  2.747467e+08      6.5902
2501   2000-01-28     93.0  3.928488e+07  5.706575e+08     11.3857
2502   2011-03-08     98.0  5.425747e+06  4.584468e+07     11.2271

      vote_average  vote_count    status  \
0            8.484       40566  Released
1            8.400       39727  Released
2            8.062       38993  Released
3            8.534       36255  Released
4            7.610       34348  Released
...            ...         ...       ...
2498         6.285        2223  Released
2499         7.000        1051  Released
2500         7.900        4215  Released
2501         7.100         475  Released
2502         7.900        2514  Released

                                               overview        profit  roi_pct
0     The adventures of a group of explorers who mak...  5.816067e+08   352.49
1     Cobb, a skilled thief who commits corporate es...  6.790306e+08   424.39
2     When an unexpected enemy emerges and threatens...  1.298816e+09   590.37
3     Batman raises the stakes in his war on crime. ...  8.195584e+08   443.00
4     In the 22nd century, a paraplegic Marine is di...  2.686706e+09  1133.63
...                                                 ...           ...      ...
2498  In the year 2019, a plague has transformed alm...  3.141719e+07   157.09
2499  Phil and Claire Foster fear that their mild-ma... -5.619119e+06    -6.03
2500  Young teenager Sam Witwicky becomes involved i...  1.646479e+08   149.55
2501  Evil pirate Burger Beard is in search of the f...  5.313726e+08  1352.61
2502  Jerry, a small-town Minnesota car salesman is ...  4.041893e+07   744.95

[2503 rows x 14 columns]

In [27]:

# 12. Final information
print("\nFinal shape:", df_clean.shape)

print("\nFinal data types:")
print(df_clean.dtypes)

print("\nFinal missing values:")
print(df_clean.isnull().sum())
print(df_clean.head())

Final shape: (2503, 14)

Final data types:
movie_id                      int64
title                           str
original_language               str
release_date         datetime64[us]
runtime                     float64
budget                      float64
revenue                     float64
popularity                  float64
vote_average                float64
vote_count                    int64
status                          str
overview                        str
profit                      float64
roi_pct                     float64
dtype: object

Final missing values:
movie_id              0
title                 0
original_language     0
release_date          0
runtime               0
budget                0
revenue               0
popularity            0
vote_average          0
vote_count            0
status                0
overview              0
profit                0
roi_pct              90
dtype: int64
   movie_id            title original_language release_date  runtime  \
0    157336     Interstellar                en   2014-11-05    169.0
1     27205        Inception                en   2010-07-15    148.0
2     24428     The Avengers                en   2012-04-25    143.0
3       155  The Dark Knight                en   2008-07-16    152.0
4     19995           Avatar                en   2009-12-16    162.0

        budget       revenue  popularity  vote_average  vote_count    status  \
0  165000000.0  7.466067e+08     73.0452         8.484       40566  Released
1  160000000.0  8.390306e+08     55.8497         8.400       39727  Released
2  220000000.0  1.518816e+09     72.2515         8.062       38993  Released
3  185000000.0  1.004558e+09     60.5510         8.534       36255  Released
4  237000000.0  2.923706e+09     48.1996         7.610       34348  Released

                                            overview        profit  roi_pct
0  The adventures of a group of explorers who mak...  5.816067e+08   352.49
1  Cobb, a skilled thief who commits corporate es...  6.790306e+08   424.39
2  When an unexpected enemy emerges and threatens...  1.298816e+09   590.37
3  Batman raises the stakes in his war on crime. ...  8.195584e+08   443.00
4  In the 22nd century, a paraplegic Marine is di...  2.686706e+09  1133.63

In [28]:
 #Export cleaned data
df_clean.to_csv("movies_cleaned.csv", index=False)

print("\nCleaned CSV exported successfully!")

Cleaned CSV exported successfully!

In [29]:
df_clean

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview,profit,roi_pct
0,157336,Interstellar,en,2014-11-05,169.0,1.650000e+08,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...,5.816067e+08,352.49
1,27205,Inception,en,2010-07-15,148.0,1.600000e+08,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es...",6.790306e+08,424.39
2,24428,The Avengers,en,2012-04-25,143.0,2.200000e+08,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...,1.298816e+09,590.37
3,155,The Dark Knight,en,2008-07-16,152.0,1.850000e+08,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...,8.195584e+08,443.00
4,19995,Avatar,en,2009-12-16,162.0,2.370000e+08,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di...",2.686706e+09,1133.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2498,19901,Daybreakers,en,2010-01-06,98.0,2.000000e+07,5.141719e+07,6.5762,6.285,2223,Released,"In the year 2019, a plague has transformed alm...",3.141719e+07,157.09
2499,1368167,Date Night,en,1995-04-08,88.0,9.321480e+07,8.759568e+07,8.2930,7.000,1051,Released,Phil and Claire Foster fear that their mild-ma...,-5.619119e+06,-6.03
2500,1368168,Transformers,en,1987-06-27,144.0,1.100988e+08,2.747467e+08,6.5902,7.900,4215,Released,Young teenager Sam Witwicky becomes involved i...,1.646479e+08,149.55
2501,1368169,The SpongeBob Movie: Sponge Out of Water,en,2000-01-28,93.0,3.928488e+07,5.706575e+08,11.3857,7.100,475,Released,Evil pirate Burger Beard is in search of the f...,5.313726e+08,1352.61
2502,1368170,Fargo,en,2011-03-08,98.0,5.425747e+06,4.584468e+07,11.2271,7.900,2514,Released,"Jerry, a small-town Minnesota car salesman is ...",4.041893e+07,744.95

In [30]:
from sqlalchemy import create_engine
engine = create_engine(
    "mysql+pymysql://root:root@localhost/movies"
)

print("Engine created successfully!")

Engine created successfully!

In [31]:
df_clean.to_sql(
     'movies',
    if_exists='replace',
    con=engine,
    index=False)

2503