In [11]:
import pandas as pd

In [12]:
df_mg = pd.read_csv('movie_genres.csv')

In [13]:
df_mg

      movie_id  genre_id
0       157336        12
1       157336        18
2       157336       878
3        27205        28
4        27205       878
...        ...       ...
6883      9705        53
6884      8914        28
6885      1429        80
6886     57800     10751
6887    456740        27

[6888 rows x 2 columns]

In [14]:
df_mg.head()

   movie_id  genre_id
0    157336        12
1    157336        18
2    157336       878
3     27205        28
4     27205       878

In [15]:
df_mg.columns

Index(['movie_id', 'genre_id'], dtype='str')

In [8]:
df_mg.info()

<class 'pandas.DataFrame'>
RangeIndex: 6888 entries, 0 to 6887
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  6888 non-null   int64
 1   genre_id  6888 non-null   int64
dtypes: int64(2)
memory usage: 107.8 KB

In [28]:
df_mg.shape

(6888, 2)

In [30]:
# 2. Convert datatypes
df_mg["movie_id"] = df_mg["movie_id"].astype(int)
df_mg["genre_id"] = df_mg["genre_id"].astype(int)

In [35]:
#check duplicate rows
print("Duplicate rows:", df_mg.duplicated().sum())

Duplicate rows: 10

In [40]:
# Remove duplicate mappings
df_mg_clean = (df_mg.drop_duplicates().reset_index(drop=True))

In [41]:
df_mg_clean

      movie_id  genre_id
0       157336        12
1       157336        18
2       157336       878
3        27205        28
4        27205       878
...        ...       ...
6873      7461        53
6874      7461        80
6875     19901        28
6876     19901        14
6877     19901       878

[6878 rows x 2 columns]

In [42]:
# 3. Load primary tables
df_movies = pd.read_csv('movies_cleaned.csv')
df_genres = pd.read_csv('genres_cleaned.csv')

In [44]:
# 2. Validate foreign keys against referenced tables
valid_movies = set(df_movies['movie_id'])
valid_genres = set(df_genres['genre_id'])

In [45]:
# 4. Filter out any invalid IDs
df_mg_clean = df_mg_clean[
    df_mg_clean['movie_id'].isin(valid_movies) & 
    df_mg_clean['genre_id'].isin(valid_genres)
]

In [48]:
# 5.  cleaned dataset
df_mg_clean.to_csv('movie_genres_cleaned.csv', index=False)
print("Movie_genres dataset cleaned successfully!")

Movie_genres dataset cleaned successfully!

In [49]:
df_mg_clean

      movie_id  genre_id
0       157336        12
1       157336        18
2       157336       878
3        27205        28
4        27205       878
...        ...       ...
6873      7461        53
6874      7461        80
6875     19901        28
6876     19901        14
6877     19901       878

[6878 rows x 2 columns]

In [ ]:
#Load → Convert datatypes → Remove duplicates → Check foreign keys → Save

In [50]:
from sqlalchemy import create_engine
engine = create_engine(
    "mysql+pymysql://root:root@localhost/movies"
)

print("Engine created successfully!")

Engine created successfully!

In [51]:
df_mg_clean.to_sql(
     'movie_genres',
    if_exists='replace',
    con=engine,
    index=False)

6878